name: CI Build

on:
  pull_request:
    branches: [ "master" ]

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      Solution_Name: ./BalazorRealtimeCharts.sln      
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name

    - name: Build
      run: dotnet build $env:Solution_Name --no-restore
